apiVersion: apps/v1
kind: Deployment
metadata:
  name: smallapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smallapp
  template:
    metadata:
      labels:
        app: smallapp
    spec:
      containers:
        - name: smallapp
          image: rndmz/smallapp